### ISSUE TITLE
How to compile on Windows?

### ISSUE THREAD

**Issue by cx-zzz** [rgl-epfl/large-steps-pytorch#10]
I try to build this project on my windows for a week, and unfortunately failed,  can you give me the specific process of build the project on windows? :)
The failure I met is related to libs in the ext/ (mainly numpyeigen).

**Comment by bathal1** [comment]
Hi,

The build of the Botsch-Kobbelt remesher is not currently supporting Windows, however some people have been able to make some tweaks to get it working, see this [pull request](https://github.com/sgsellan/botsch-kobbelt-remesher-libigl/pull/13) for some pointers.

**Comment by cx-zzz** [comment]
> 

thank you for your reply, i tried for some days and i installed ubuntu finally :).
