### ISSUE TITLE
How to deal with my datasets

### ISSUE THREAD

**Issue by X1aoyueyue** [rgl-epfl/large-steps-pytorch#13]
Hi,

Thank you for your excellent work, but I have a question. How should I handle my data so that it can be accepted by this framework? I only have meshes. I do not have the .blender file and the .xml file. And I have texture files of different formart.

Thank you.

**Comment by bathal1** [comment]
Hi! 

The framework takes scenes described in the [Mitsuba file format](https://mitsuba.readthedocs.io/en/stable/src/key_topics/scene_format.html), where the starting and target meshes have the respective ids `mesh-source` and `mesh-target`. 


Note that part of this repo is here to reproduce the experiments of the paper, therefore it may not be super flexible.
If you want to use this method as part of yout pipeline, I recommend you install the package `largesteps` via pip, then you will be able to use the method more freely.
