### ISSUE TITLE
Crash for simple loss on vertices

### ISSUE THREAD

**Issue by mworchel** [rgl-epfl/large-steps-pytorch#15]
Hi,

first off, thanks for the code, the package has been working flawlessly for me so far. 

I just wanted to report an esoteric issue I have encountered some time ago: in the reproducer below, computing the gradient of the sum over the vertex data produces the following error message
```
TypeError: solve(): incompatible function arguments. The following argument types are supported:
    1. solve(self, b: tensor[dtype=float32, order='C'], x: tensor[dtype=float32, order='C']) -> None
Invoked with types: cholespy.CholeskySolverF, torch.Tensor, torch.Tensor
```
whereas computing the mean does not.

In practice, the issue is not super relevant because the vertices are used in downstream computations but you might want to look into that.

```python
from largesteps.parameterize import from_differential, to_differential
from largesteps.geometry import compute_matrix
import torch

device = torch.device('cuda:0')

v = torch.rand((3, 3), dtype=torch.float32, device=device)
f = torch.tensor([[0, 1, 2]], dtype=torch.int32, device=device)

M = compute_matrix(v, f, lambda_=10)

u = to_differential(M, v)
u.requires_grad = True

v = from_differential(M, u, 'Cholesky')

want_to_crash = True

if want_to_crash:
    loss = v.sum()
else:
    loss = v.mean() 

loss.backward() # crashes here if want_to_crash = True
```

I am on Windows 10, using `PyTorch 1.13.1`, `cholespy 0.1.6`, and `largesteps 0.2.1`.

**Comment by bathal1** [comment]
Thanks for the report and the reproducer ! Somehow calling `sum` will result in a non-contiguous gradient tensor when calling `backward`, but `mean` won't. Calling the solver with `grad_output.contiguous()` seems to fix this.

**Comment by mworchel** [comment]
Thanks for looking into it; luckily a simple fix!

**Comment by wjakob** [comment]
@bathal1 : you can specify annotations to the nanobind to force the input to be contiguous. It will then basically call `.contiguous()` for you if needed (in a way that works across various frameworks). If you already have that annotation and it doesn't work, then it's potentially a nanobind bug.

Pointers: https://nanobind.readthedocs.io/en/latest/ndarray.html, https://nanobind.readthedocs.io/en/latest/api_extra.html#_CPPv4IDpEN8nanobind7ndarrayE
