### ISSUE TITLE
Solve() imcompatible function arguments 

### ISSUE THREAD

**Issue by iszihan** [rgl-epfl/large-steps-pytorch#16]
<img width="734" alt="Screen Shot 2023-04-16 at 1 08 28 PM" src="https://user-images.githubusercontent.com/36280571/232328797-86068c62-a948-4e16-bab9-25656de8134f.png">
Hello, I'm trying to use large step in my project and got this error. I checked that when I call from_differential(), both M and u have dtype of float32. Would someone know why this is happening?

**Comment by iszihan** [comment]
This mesh does have some small triangles, would this be causing the error?

**Comment by iszihan** [comment]
I didn't explicitly define the b and x that gets passed into this function as I was mainly calling from_differential and to_differential and then doing backprop through these operations. I tried just saving the argument b and the matrix M and wrote a minimal script that reproduces this error, and I uploaded them here in Google Drive https://drive.google.com/drive/folders/1RpEX5QliUbRCb0s_sIH_aRs0WcTPYDzD?usp=sharing . Thank you for your time and let me know if I can help provide more information.

**Comment by bathal1** [comment]
The reproducer you shared runs fine on my end. What version of Pytorch are you using, and on which device ?

**Comment by iszihan** [comment]
I was using torch 2.0.0. And actually this just got fixed by calling .contiguous() on b and x before the solve! Thanks for looking into it.

**Comment by bathal1** [comment]
Indeed, `cholespy` expects contiguous arrays as input.
