### ISSUE TITLE
render faster

### ISSUE THREAD

**Issue by wpalfi** [rgl-epfl/large-steps-pytorch#3]
fyi you can speed up rendering by ~50%. Replace
https://github.com/rgl-epfl/large-steps-pytorch/blob/e03b40e237276b0efe32d022f5886b81db45bc3c/scripts/render.py#L210-L213
by
```python
vert_light = self.sh.eval(n).contiguous()
light = dr.interpolate(vert_light[None, ...], rast, f)[0]
```

**Comment by bathal1** [comment]
Nice, thanks! Do you have any insight as to why swapping those two lines speeds up computation so much?

**Comment by wpalfi** [comment]
Because the diffuse shading is view-independent and there are less vertices than pixels.
- The argument shapes of `dr.interpolate()`  are the same in both cases.
- The argument size of `self.sh.eval()` is `B*H*W*3 = 16*512**2*3 =~ 1e7` in the original code, but only `V*3 =~ 1e5` in my version.
