### ISSUE TITLE
Running blender_render.py

### ISSUE THREAD

**Issue by samgr55** [rgl-epfl/large-steps-pytorch#5]
First of all I'd like to thank you for making this phenomenal experience and make it available for testing.
Running the nvdiffrast can be really straight forward and easy for rendering but I'm having some understanding problem with rendering the code inside the blender so please bear with me :)

How do I run the rendering inside the blender? Is it by script editor? [I tried it but it gives me errors] 
Is it by running it as command ? 

I just need to understand the methodology of rendering that in blender since it's a utility and not included in the Tutorial.

Thank you so much.

**Comment by bathal1** [comment]
Hi,
The `blender_render.py` script is intended to be run gfrom the command line like so : 
`blender -b scene.blend --python path/to/blender_render.py -- [args]`

In practice, this command call is constructed in the function `blender_render` defined in `scripts/preamble.py`. This function is called from the Jupyter Notebooks used to generate the figures.
