### ISSUE TITLE
Program exits when running from_differential

### ISSUE THREAD

**Issue by 7DBW13** [rgl-epfl/large-steps-pytorch#9]
Hi, I got problems after updating to the latest 0.2.0 version. When my program invoked the `from_differential` function, it got stuck for a little while, and then exited directly. Nothing (warnings/errors/...) was shown on my prompt, and so I could not figure out what happened. However, the initial 0.1.1 version worked well. Tested on: Windows 10, AMD Ryzen 9 5900HX with Radeon Graphics @ 3.30GHz 16GB, GeForce RTX 3070 Laptop GPU 8GB.

**Comment by bathal1** [comment]
Hello,
Thanks for reporting this. Can you please provide a minimal reproducer so I can look into it?

**Comment by bathal1** [comment]
Should be fixed by updating `cholespy`:
```bash=
pip install cholespy --upgrade
```
